{
 "title": "NiFi Cluster Health",
 "description": "General view of Nifi \r\n",
 "tags": [ "NiFi" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "nifi_cluster",
    "query": "label_values(nifi_nodes_status,cluster)"
   },
   {
    "name": "nifi_node",
    "label": "NiFi Instance",
    "query": "label_values(nifi_nodes_status{cluster=~\"$nifi_cluster\"}, exported_instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "NiFI Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "nifi_cluster_version_info{cluster='$nifi_cluster'}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "General view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$nifi_node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "repeat": "nifi_node",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nifi_nodes_status{cluster='$nifi_cluster', exported_instance=~\"$nifi_node\"}"
    }
   ]
  },
  { "title": "Nodes - Queued Items", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$nifi_node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "repeat": "nifi_node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nifi_node_queuedItems{cluster='$nifi_cluster'}"
    }
   ]
  },
  { "title": "Nodes - Active Thread Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "$nifi_node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "repeat": "nifi_node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nifi_node_activeThreadCount{cluster='$nifi_cluster'}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Flow Files Queued",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nifi_cluster_flowFilesQueued{cluster='$nifi_cluster'}"
    }
   ]
  },
  {
   "title": "Bytes Queued",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 27 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "nifi_cluster_bytesQueued{cluster='$nifi_cluster'}"
    }
   ]
  },
  {
   "title": "General proccessor counters ",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "nifi_cluster_stoppedCount{cluster='$nifi_cluster'}",
     "legendFormat": "Stopped Count"
    },
    {
     "expr": "nifi_cluster_invalidCount{cluster='$nifi_cluster'}",
     "legendFormat": "Invalid Count"
    },
    {
     "expr": "nifi_cluster_runningCount{cluster='$nifi_cluster'}",
     "legendFormat": "Running Count"
    }
   ]
  },
  { "title": "Queued Item", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Queue item per PG",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nifi_amount_items_queued{cluster='$nifi_cluster'}",
     "legendFormat": "{{processorName}}"
    }
   ]
  }
 ]
}